name: Repository Dispatch demo
on:
  repository_dispatch: 
    types: [deploy_app]

jobs:
  demoJob:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Print App info
      run: |
        Echo "Workflow Triggered!!"
        Echo "My app info:"
        Echo " My Event name: ${{github.event.action}} "
        Echo " App name: ${{github.event.client_payload.app}}"
        Echo "Enviroment name: ${{github.event.cilent_payload.env}}"
      
    
