name: Repository Dispatch demo
on:
  repository_dispatch: 
    types: [deploy_app]

jobs:
  demoJob:
    runs-on: ubuntu-latest
    steps:
      - name: Print App info
        run: |
          echo "Workflow Triggered!!"
          echo "My app info:"
          echo " My Event name: ${{github.event.action}} "
          echo " App name: ${{github.event.client_payload.app}}"
          echo "Enviroment name: ${{github.event.client_payload.env}}"
      
    
